# -*- coding: utf-8 -*-
"""day-4-hypothesis-creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QScmnt3329iEEeSAT6fsLSpeggDxMkGC

# 🧪 Machine Learning Research Roadmap

## Day 4: Hypothesis Creation

> A hypothesis is a testable prediction about what we expect to happen.

In Day 3, we learned how to formulate strong research questions.

Today, we'll use the Titanic dataset to transform observations into hypotheses and learn how researchers create H₀ and H₁ before conducting experiments.
"""

import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/yashashree01/titanic-dataset-for-ml-research-roadmap/train.csv")

print("Dataset Shape:", train.shape)
train.head()

"""# 🤔 Why Do We Need Hypotheses?

Suppose we observe something interesting in the Titanic dataset.

For example:

* Women appear to survive more often than men.
* First-class passengers appear to survive more often than third-class passengers.

Observations alone are not enough.

Researchers transform observations into testable predictions called hypotheses.

Today, we'll use real Titanic data to do exactly that.

"""

train.groupby("Sex")["Survived"].mean()

"""# 🔮 From Observation to Hypothesis

### Observation

Survival rates differ between male and female passengers.

### Research Question

Does passenger gender influence survival probability?

### Prediction

Female passengers will have higher survival rates.

### Hypothesis

Passenger gender significantly influences survival probability.

---

Researchers use data observations to create hypotheses that can later be tested.

# ⚖️ Null and Alternative Hypotheses

Researchers do not directly test a hypothesis.

Instead, they compare two competing statements.

### H₀ (Null Hypothesis)

Passenger gender has no effect on survival probability.

### H₁ (Alternative Hypothesis)

Passenger gender influences survival probability.

The goal of research is to determine which statement is better supported by evidence.
"""

gender_survival = train.groupby("Sex")["Survived"].mean()

print(gender_survival)

"""# 📊 Interpreting the Evidence

If survival rates differ substantially between males and females, this provides evidence against H₀.

However, observing a difference is not enough.

Researchers need statistical tests to determine whether the difference is significant or could have occurred by chance.

This is why hypotheses are important—they prepare us for formal testing.

# 🧮 Hypotheses and Statistical Testing

Many statistical tests compare two hypotheses:

### Null Hypothesis

H₀

### Alternative Hypothesis

H₁

The general decision process is:

Evidence

↓

Statistical Test

↓

Reject H₀ or Fail to Reject H₀

Researchers do not prove H₁.

Instead, they gather enough evidence to reject H₀.

# 🧮 Mathematical Representation of Hypotheses

In research, hypotheses are often written using mathematical notation.

---

### Example 1 — Gender and Survival

Null Hypothesis:

H₀: Gender has no effect on survival probability.

Mathematically:

H₀: p_male = p_female

Alternative Hypothesis:

H₁: p_male ≠ p_female

where:

* p_male = survival probability of male passengers
* p_female = survival probability of female passengers

---

### Example 2 — Passenger Age

Null Hypothesis:

H₀: μ_survived = μ_not_survived

Alternative Hypothesis:

H₁: μ_survived ≠ μ_not_survived

where:

* μ_survived = mean age of survivors
* μ_not_survived = mean age of non-survivors

---

### Example 3 — Model Performance

Research Question:

Does feature selection improve model accuracy?

Null Hypothesis:

H₀: Accuracy_before = Accuracy_after

Alternative Hypothesis:

H₁: Accuracy_before ≠ Accuracy_after

---

### Why Use Mathematical Notation?

Mathematical notation removes ambiguity and makes hypotheses precise, measurable, and suitable for statistical analysis.
"""

# Survival rate by gender

train.groupby("Sex")["Survived"].mean()

"""Using the observed survival rates, we can formulate:

H₀: p_male = p_female

H₁: p_male ≠ p_female

These hypotheses can later be tested using statistical methods.

"""

# Male survival probability

male = train[train["Sex"] == "male"]

p_male = male["Survived"].sum() / len(male)

# Female survival probability

female = train[train["Sex"] == "female"]

p_female = female["Survived"].sum() / len(female)

print("p_male =", round(p_male, 4))
print("p_female =", round(p_female, 4))

"""# 👨👩 Creating a Hypothesis from Gender Data

## Step 1 — Observation

The survival probability for male passengers is:

p_male = 0.1889

The survival probability for female passengers is:

p_female = 0.7420

The difference is substantial.

---

## Step 2 — Research Question

Does passenger gender influence survival probability?

---

## Step 3 — Prediction

Female passengers may have a higher probability of survival than male passengers.

---

## Step 4 — Hypothesis

Passenger gender significantly influences survival probability.

---

## Step 5 — Mathematical Form

### Null Hypothesis (H₀)

p_male = p_female

Passenger gender has no effect on survival probability.

### Alternative Hypothesis (H₁)

p_male ≠ p_female

Passenger gender influences survival probability.

---

## Research Insight

The large difference between the observed probabilities motivates the creation of a hypothesis.

Researchers then collect evidence to determine whether the observed difference reflects a genuine relationship or occurred by chance.

"""

survived = train[train["Survived"] == 1]

not_survived = train[train["Survived"] == 0]

mu_survived = survived["Age"].mean()

mu_not_survived = not_survived["Age"].mean()

print("μ_survived =", round(mu_survived, 2))
print("μ_not_survived =", round(mu_not_survived, 2))

"""# 👶 Creating a Hypothesis from Age Data

## Step 1 — Observation

The average age of survivors is:

μ_survived = 28.34

The average age of non-survivors is:

μ_not_survived = 30.63

The two values are different.

---

## Step 2 — Research Question

Does passenger age influence survival probability?

---

## Step 3 — Prediction

Younger passengers may have a higher chance of survival than older passengers.

---

## Step 4 — Hypothesis

Passenger age significantly influences survival probability.

---

## Step 5 — Mathematical Form

### Null Hypothesis (H₀)

μ_survived = μ_not_survived

Passenger age has no effect on survival.

### Alternative Hypothesis (H₁)

μ_survived ≠ μ_not_survived

Passenger age influences survival.

---

## Research Insight

A hypothesis is not created randomly.

It is derived from observations in the data and expressed as a testable prediction.

"""

pclass_survival = train.groupby("Pclass")["Survived"].mean()

print(pclass_survival)

"""# 🎟️ Creating a Hypothesis from Passenger Class Data

## Step 1 — Observation

The survival probabilities differ across passenger classes.

This suggests that passenger class may be related to survival outcomes.

---

## Step 2 — Research Question

Does passenger class influence survival probability?

---

## Step 3 — Prediction

Passengers in higher classes may have a higher probability of survival than passengers in lower classes.

---

## Step 4 — Hypothesis

Passenger class significantly influences survival probability.

---

## Step 5 — Mathematical Form

### Null Hypothesis (H₀)

Survival probability is independent of passenger class.

Mathematically:

P₁ = P₂ = P₃

where:

* P₁ = survival probability of first-class passengers
* P₂ = survival probability of second-class passengers
* P₃ = survival probability of third-class passengers

---

### Alternative Hypothesis (H₁)

At least one passenger class has a different survival probability.

Mathematically:

P₁, P₂, and P₃ are not all equal.

---

## Research Insight

Observing differences between groups often motivates the creation of hypotheses.

Researchers then gather evidence to determine whether the observed differences represent a genuine relationship.

"""

# 🧩 A Framework for Creating Hypotheses

The process used in this notebook can be applied to any dataset.

---

## Step 1 — Observe the Data

Look for patterns, differences, trends, or unusual behavior.

↓

## Step 2 — Formulate a Research Question

Ask what relationship or effect may exist.

↓

## Step 3 — Make a Prediction

State what you expect to happen.

↓

## Step 4 — Create a Hypothesis

Convert the prediction into a clear, testable statement.

↓

## Step 5 — Write H₀ and H₁

H₀ represents no effect or no relationship.

H₁ represents an effect or relationship.

---

### General Workflow

Observation

↓

Research Question

↓

Prediction

↓

Hypothesis

↓

H₀ and H₁

↓

Future Statistical Testing

---

A strong hypothesis is specific, measurable, testable, and falsifiable.

"""# 🎯 Mini Exercise

Using the Titanic dataset, create a hypothesis for each observation below.

---

## Observation 1

Female passengers have a higher survival rate than male passengers.

### Research Question

---

### Prediction

---

### Hypothesis

---

---

## Observation 2

The average age of survivors differs from the average age of non-survivors.

### Research Question

---

### Prediction

---

### Hypothesis

---

---

### Bonus Challenge

For one of your hypotheses:

Write H₀ and H₁ using mathematical notation.

# ✅ Key Takeaways

In this chapter, we learned:

* A hypothesis is a testable prediction.
* Hypotheses are created from observations in data.
* Research questions and hypotheses are not the same thing.
* Strong hypotheses are specific, measurable, and falsifiable.
* Researchers formulate both H₀ and H₁ before conducting formal tests.

---

### Day 4 Workflow

Observation

↓

Research Question

↓

Prediction

↓

Hypothesis

↓

H₀ and H₁

↓

Future Statistical Testing

---

### Remember

A good hypothesis is not about being right.

A good hypothesis is about being testable.

# 🚀 Next Chapter

## Day 5 — Literature Review

Researchers do not begin by running experiments immediately.

Before conducting research, they investigate:

* What has already been discovered
* What methods have already been used
* What limitations exist in previous studies
* What research gaps remain unanswered

In the next chapter, we'll learn how to perform a literature review and use existing knowledge to guide future research.

# 🔗 Continue Learning

This notebook is part of the **Machine Learning Research Roadmap** series.

### GitHub Repository

[https://github.com/Yashashree-Joshi/machine-learning-research-roadmap](http://)


### Day 4 GitHub Chapter

[https://github.com/Yashashree-Joshi/machine-learning-research-roadmap/tree/main/Day-04-Hypothesis-Creation](http://)

### Dataset Used

Titanic Research Starter Pack

[https://www.kaggle.com/datasets/yashashree01/titanic-dataset-for-ml-research-roadmap](http://)

---

### Previous Chapter

📖 Day 3 — Research Question Formulation

[https://www.kaggle.com/code/yashashree01/day-3-research-question-formulation](http://)

---

### Next Chapter

🚀 Day 5 — Literature Review
"""