# -*- coding: utf-8 -*-
"""day-3-research-question-formulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uj0lXmvr29SY5Z-Vly-UjGrXpxb-3_J9

# 🎯 Machine Learning Research Roadmap

## Day 3: Research Question Formulation

> Better questions lead to better research.

---

In Day 1, we learned that research begins with questions.

In Day 2, we learned the Machine Learning Research Workflow.

Today, we'll learn how researchers transform broad ideas into clear, measurable, and researchable questions.
"""

import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/yashashree01/titanic-dataset-for-ml-research-roadmap/train.csv")

print("Shape:", train.shape)
train.head()

"""# 🤔 A Common Beginner Mistake

Many beginners see a dataset and immediately say:

"I want to build a model."

Researchers ask:

"What question can this dataset help me answer?"

The same dataset can generate many different research questions.

# **Explore the data**
"""

train.info()

train.describe()

"""# ❌ Bad Questions vs ✅ Good Questions

Using the Titanic dataset:

### ❌ Bad Question

Can machine learning predict survival?

Problems:

* Too generic
* No clear experiment
* No clear variable of interest

---

### ✅ Better Question

Does passenger age influence survival probability?

Why?

* Specific variable
* Measurable outcome
* Can be tested using data

---

### ✅ Strong Research Question

Does feature selection improve Titanic survival prediction performance?

Why?

* Specific
* Measurable
* Researchable
* Leads directly to an experiment

"""

train[["Age", "Survived"]].head()

train.groupby("Survived")["Age"].mean()

"""Question:
Does age influence survival?

↓

Look at the data

↓

Gather evidence

# 🔍 Generating Research Questions from Data

Researchers often discover questions by exploring a dataset.

Let's examine some Titanic features and see what research questions emerge.

Instead of starting with a model, we'll start with observations.
"""

# Explore survival by gender

train.groupby("Sex")["Survived"].mean().sort_values(ascending=False)

"""### Observation

If survival rates differ between males and females, this suggests that gender may influence survival outcomes.

### Possible Research Questions

❌ Bad Question

Can machine learning predict survival?

✅ Better Question

Does passenger gender influence survival probability?

✅ Strong Research Question

Does including gender-related features improve Titanic survival prediction performance?

"""

# Average age by survival status

train.groupby("Survived")["Age"].mean()

"""# 👶 Age and Survival

Researchers often investigate whether age influences outcomes.

### Observation

The average age differs between passengers who survived and those who did not survive.

### Possible Research Questions

❌ Bad Question

Is age important?

Problems:

* Too vague
* Not measurable

---

✅ Better Question

Does passenger age influence survival probability?

---

✅ Strong Research Question

Can age-related features improve Titanic survival prediction performance?

### Research Insight

Notice how a simple observation can generate multiple research questions with different levels of quality.

"""

# Survival rate by passenger class

train.groupby("Pclass")["Survived"].mean().sort_values(ascending=False)

"""# 🎟️ Passenger Class and Survival

Passenger class may influence access to resources, cabin location, and evacuation opportunities.

### Observation

Survival rates differ across passenger classes.

### Possible Research Questions

❌ Bad Question

Does class matter?

Problems:

* Ambiguous
* Poorly defined
* Not measurable

---

✅ Better Question

Does passenger class influence survival probability?

---

✅ Strong Research Question

Does including passenger class improve Titanic survival prediction performance?

### Research Insight

The same observation can generate multiple questions.

The goal is to formulate a question that is:

* Specific
* Measurable
* Researchable
* Relevant
* Focused

# 🧩 A Framework for Creating Research Questions

Use the following process on any dataset:

### Step 1 — Explore the Data

Look for patterns, trends, missing values, and unusual observations.

↓

### Step 2 — Identify an Interesting Observation

Example:

Female passengers appear to survive more often.

↓

### Step 3 — Ask a Better Question

Instead of:

"Can machine learning predict survival?"

Ask:

"Does passenger gender influence survival probability?"

↓

### Step 4 — Make It Researchable

Transform it into:

"Does including gender-related features improve Titanic survival prediction performance?"

---

### Formula

Observation

↓

Better Question

↓

Research Question

↓

Hypothesis

↓

Experiment

# 🎯 Mini Exercise

You are given the Titanic dataset.

Create one research question for each feature below:

### Age

Your Question:

---

---

### Sex

Your Question:

---

---

### Passenger Class (Pclass)

Your Question:

---

---

### Bonus

Which of your three questions is the strongest?

Why?

# ✅ Key Takeaways

In this chapter, we learned:

* A topic is not the same as a research question.
* Good research questions are specific, measurable, and researchable.
* Research questions often emerge from observations in data.
* The same dataset can generate many different research questions.
* Strong questions naturally lead to hypotheses and experiments.

---

### Remember

Bad Research:

Dataset → Model → Accuracy

Good Research:

Observation → Question → Hypothesis → Experiment → Evidence

# 🚀 Next Chapter

## Day 4 — Hypothesis Creation

A research question identifies what we want to investigate.

A hypothesis predicts what we expect to happen.

In the next chapter, we'll learn:

* Null vs Alternative Hypotheses
* Good vs Bad Hypotheses
* Testable Predictions
* Hypothesis Design using Titanic Data

A strong research question should naturally lead to a strong hypothesis.

# 🔗 Continue Learning

This notebook is part of the **Machine Learning Research Roadmap** series.

### GitHub Repository

https://github.com/Yashashree-Joshi/machine-learning-research-roadmap

### Day 3 GitHub Chapter

https://github.com/Yashashree-Joshi/machine-learning-research-roadmap/tree/main/Day-03-Research-Question-Formulation

---

### Resources

📦 Titanic Research Starter Pack

https://www.kaggle.com/datasets/yashashree01/titanic-dataset-for-ml-research-roadmap

---

### Previous Chapter

📖 Day 2 — The Machine Learning Research Workflow

https://github.com/Yashashree-Joshi/machine-learning-research-roadmap/tree/main/Day-02-The-ML-Research-Workflow

---

### Next Chapter

🚀 Day 4 — Hypothesis Creation

Learn how researchers transform research questions into testable hypotheses using null and alternative hypotheses, predictions, and experimental design.
"""