# -*- coding: utf-8 -*-
"""day-2-the-machine-learning-research-workflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TOT3zsCXWseeqKFxAnBwiw898y8kB3FI

# 🧠 Machine Learning Research Roadmap

## Day 2: The Machine Learning Research Workflow

> From Research Questions to Evidence-Based Conclusions

---

📦 **Dataset Used**

Titanic Research Starter Pack

---

📚 **Companion GitHub Chapter**

(https://github.com/Yashashree-Joshi/machine-learning-research-roadmap/tree/5597bd1c90a40af88b060f07169eb18e5d1b43f9/Day-02-The-ML-Research-Workflow)

---

# 🤔 A Common Misconception

Many beginners think Machine Learning Research looks like this:

```text
Dataset
   ↓
Model
   ↓
Accuracy
```

Build a model.

Measure accuracy.

Move on.

---

Researchers think differently.

They ask:

- What problem am I solving?
- What question am I investigating?
- What hypothesis am I testing?
- How will I evaluate the results?

Research is not random experimentation.

Research is a structured process for generating evidence.

In this chapter, we'll learn the complete Machine Learning Research Workflow and apply it to a real-world example using the Titanic dataset.
"""

#Libraries needed
import pandas as pd

train = pd.read_csv(
    "/kaggle/input/datasets/yashashree01/titanic-dataset-for-ml-research-roadmap/train.csv"
)

print("Dataset Shape:", train.shape)

train.head()

train.info()

train.describe()

"""# 📊 Understanding the Dataset

Before formulating a research question, researchers first understand the available data.

From the outputs above, we can observe:

- The dataset contains passenger demographic and travel information.
- Some features contain missing values.
- The target variable is **Survived**.
- Features have different data types and scales.

---

### Initial Observations

Some questions immediately arise:

1. Do missing values affect model performance?
2. Which features are most important for predicting survival?
3. Does feature selection improve model accuracy?
4. Which evaluation metric should we prioritize?

These observations help transform a dataset into a research opportunity.

# ❓ Formulating a Research Question

A dataset alone is not research.

Research begins when we ask a specific question.

Based on our observations, we will investigate:

> Does feature selection improve Titanic survival prediction performance?

---

## Why This Question?

We observed:

- Multiple input features
- Missing values
- Different feature types

Not every feature may contribute equally to prediction.

Removing less informative features may improve model performance and reduce noise.

This gives us a testable research question.

# 📝 Hypothesis

A hypothesis is a testable prediction.

For our research question:

> Does feature selection improve Titanic survival prediction performance?

We propose the following hypothesis:

### H₁ (Alternative Hypothesis)

Removing less informative features will improve model performance by reducing noise and helping the model focus on relevant information.

### H₀ (Null Hypothesis)

Feature selection has no significant effect on model performance.

---

The next step is to design an experiment that can test this hypothesis.
"""

# Check missing values

train.isnull().sum().sort_values(ascending=False)

"""# ⚙️ Experiment Design

To test our hypothesis, we will build a baseline model using a selected set of features.

Future chapters will compare this model against alternative feature-selection strategies.

---

## Evaluation Metric

We will use:

- Accuracy
- F1 Score

"""

missing = train.isnull().sum().sort_values(ascending=False)

missing[missing > 0]

"""# 🔍 Interpreting the Evidence

The missing-value analysis reveals three important observations:

| Feature | Missing Values |
|----------|---------------|
| Cabin | 687 |
| Age | 177 |
| Embarked | 2 |

---

### Research Decisions

#### Cabin

More than 75% of the values are missing.

Decision:

Drop the feature.

---

#### Age

The feature is potentially important for survival prediction.

Decision:

Keep the feature and impute missing values.

---

#### Embarked

Only two values are missing.

Decision:

Fill missing values using the most frequent category.

---

This process demonstrates an important research principle:

> Data-driven decisions should be justified using evidence.
"""

# Select features for our baseline model

features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]

train_model = train[features + ["Survived"]].copy()

train_model.head()

# Handle missing values

train_model["Age"] = train_model["Age"].fillna(
    train_model["Age"].median()
)

train_model["Embarked"] = train_model["Embarked"].fillna(
    train_model["Embarked"].mode()[0]
)

# Convert categorical features

train_model["Sex"] = train_model["Sex"].map(
    {"male": 0, "female": 1}
)

train_model = pd.get_dummies(
    train_model,
    columns=["Embarked"],
    drop_first=True
)

train_model.head()

"""# 🤖 Baseline Model

We now train our first machine learning model.

This serves as a baseline against which future experiments can be compared.

For simplicity, we will use Logistic Regression.
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

# Features and target

X = train_model.drop("Survived", axis=1)
y = train_model["Survived"]

# Train-test split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train model

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

# Predictions

y_pred = model.predict(X_test)

# Metrics

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", round(accuracy, 4))
print("F1 Score:", round(f1, 4))

"""# 📈 Evaluation

Our baseline Logistic Regression model achieved:

| Metric | Score |
|----------|----------|
| Accuracy | 0.8101 |
| F1 Score | 0.7639 |

---

## What Do These Results Mean?

The model correctly predicted survival outcomes for approximately 81% of passengers in the test set.

The F1 Score of 0.7639 indicates a good balance between precision and recall.

---

## Research Perspective

The goal of this experiment was not to achieve the highest possible score.

The goal was to establish a baseline model that future experiments can improve upon.

Researchers rarely begin with the best model.

They begin with a reproducible baseline and then test hypotheses through systematic experimentation.

# 🔍 Conclusion

In this chapter, we followed the complete Machine Learning Research Workflow:

```text
Problem
↓
Research Question
↓
Hypothesis
↓
Dataset Exploration
↓
Evidence Gathering
↓
Experiment
↓
Evaluation
```

Using the Titanic dataset, we:

- Formulated a research question
- Created a hypothesis
- Investigated missing values
- Selected features
- Built a baseline model
- Evaluated results

This demonstrates how Machine Learning Research moves from questions to evidence-based conclusions.

---

### Key Lesson

Research is not:

Dataset → Model → Accuracy

Research is:

Question → Hypothesis → Experiment → Evidence → Conclusion

# 🔗 Continue Learning

This notebook is part of the **Machine Learning Research Roadmap** series.

### GitHub Repository

https://github.com/Yashashree-Joshi/machine-learning-research-roadmap

### Day 2 GitHub Chapter

https://github.com/Yashashree-Joshi/machine-learning-research-roadmap/tree/main/Day-02-The-ML-Research-Workflow

---

### Resources

📦 Titanic Research Starter Pack

(https://www.kaggle.com/datasets/yashashree01/titanic-dataset-for-ml-research-roadmap)

---

### Next Chapter

🚀 Day 3 — Research Question Formulation

Learn how researchers transform problems into strong, testable research questions.
"""